Repository newrelic/nri-kube-events, pull requests merged in 2023-09, with the labels that each got.

#276 Fix K8s Version Format
  .github/workflows/push_pr.yml
Labels: Skip Changelog

#277 feat(workflows): Update changelog workflow to look like the one on `k8s-metadata-injection` repo
  .github/workflows/changelog.yml
Labels: ci/skip-e2e, Skip Changelog

#279 feat: Enable automatic release
  .github/renovate.json5
  .github/workflows/push_pr.yml
  .github/workflows/release.yml
  .github/workflows/security.yml
  .github/workflows/trigger_prerelease.yml
  .gitignore
  Makefile
Labels: Skip Changelog

#278 feat(dependabot): Remove dependabot
  .github/dependabot.yml
Labels: ci/skip-e2e, Skip Changelog

#287 feat(ci): Automate version bumps
  .github/workflows/push_pr.yml
  .github/workflows/release.yml
  src/utils/version-update.go
Labels: ci/skip-e2e, Skip Changelog

#291 fix(ci): Make GitHub runner consistent on all workflows
  .github/workflows/push_pr.yml
Labels: Skip Changelog

#293 fix(ci): Fix typo
  .github/workflows/release.yml
Labels: ci/skip-e2e, Skip Changelog

#294 fix(ci): Update changelog for PR 293
  CHANGELOG.md
Labels: ci/skip-e2e

#296 fix(ci): Fix `release.yml` workflow
  .github/workflows/release.yml
  CHANGELOG.md
Labels: ci/skip-e2e

#298 Simplify PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Skip Changelog

#299 Run checklog workflow when labels change
  .github/workflows/changelog.yml
Labels: Skip Changelog

#300 Add debugging information to the workflow
  .github/workflows/changelog.yml
Labels: Skip Changelog

#301 Make changelog.yml workflow run when labels change
  .github/workflows/changelog.yml
Labels: Skip Changelog

#302 Update CHANGELOG.md
  CHANGELOG.md
Labels: ci/skip-e2e

#308 ci: Update 'Security Scan' to use reusable workflow
  .github/workflows/security.yml
Labels: ci/skip-e2e, Skip Changelog

#309 ci: Add Slack notifications to all workflows that do not involve pull requests
  .github/workflows/nightly.yml
  .github/workflows/release-chart.yml
  .github/workflows/release-integration.yml
  .github/workflows/release.yml
  .github/workflows/trigger_prerelease.yml
Labels: ci/skip-e2e, Skip Changelog

#310 ci: Use reusable workflow for 'Trigger prerelease creation'
  .github/workflows/trigger_prerelease.yml
Labels: ci/skip-e2e, Skip Changelog

#311 doc: Update CHANGELOG.md
  CHANGELOG.md
Labels: ci/skip-e2e
